### ISSUE TITLE
MySocialApp Error Catch Issue

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#10]
I can't catch error for all functions which i call.

For  thees examples,when I call "blockingConnect" or "connect" functions
I can't catch error if my userName or password is incorrect
But console got all errors.

Please see attached screenshots
Example 1.
![screen shot 2018-06-22 at 10 40 08 pm](https://user-images.githubusercontent.com/9318170/41795804-2afc5aa8-7675-11e8-8543-c023e36e00c9.png)
Console Error Log
![screen shot 2018-06-22 at 10 38 26 pm](https://user-images.githubusercontent.com/9318170/41795824-34d4e77a-7675-11e8-9078-18fabffe3d79.png)
Example 2
![screen shot 2018-06-22 at 10 50 59 pm](https://user-images.githubusercontent.com/9318170/41795843-47fb8412-7675-11e8-9dae-4b6fc09a8bd7.png)
Example 3
![screen shot 2018-06-22 at 10 53 28 pm](https://user-images.githubusercontent.com/9318170/41795876-67fe4f7e-7675-11e8-9129-4053b85cd605.png)

Can You show me code example how can I catch error?

* Swift version: 4.2
* xCode version: 9.4.1

Thank You.
Best regards.

**Comment by Gobountz** [comment]
@Valodya89 the errors were sometimes not provided to the caller. The problem has been solved in the 1.0.14 version.

Best regards.
