### ISSUE TITLE
'MySocialApp', '~> 1.0.14' version update issue

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#11]
I can't update the new version (1.0.14)

When I try pod update 

![screen shot 2018-06-25 at 10 30 00 am](https://user-images.githubusercontent.com/9318170/41833789-d1e669d2-7862-11e8-97e4-09ab982e5853.png)

I got this error 
"CocoaPods could not find compatible versions for pod "MySocialApp":
  In Podfile:
    MySocialApp (~> 1.0.14)"
![screen shot 2018-06-25 at 10 27 37 am](https://user-images.githubusercontent.com/9318170/41833836-0442f382-7863-11e8-8f47-2d2834d22662.png)

**Comment by Gobountz** [comment]
Indeed, the podspec didn't update as expected. This is fixed now.

Best regards.

**Comment by Valodya89** [comment]
@Gobountz Thank You

But I still got same error , when I use 'MySocialApp', '~> 1.0.14'  pod update

**Comment by Gobountz** [comment]
@Valodya89 still podspec problem ... I published the 1.0.15 version which seems to be ok.

Best regards.
