### ISSUE TITLE
EVENT SUBSCRIPTION 

### ISSUE THREAD

**Issue by herve-web-isi** [MySocialApp/mysocialapp-swift-client#12]
**Describe the bug**
About event participation, there is this  possible status 
WANT_TO_PARTICIPATE
WAITING_CONFIRMATION
CONFIRMED
WAITING_FOR_FREE_SEAT
NO_RESPONSE
NOT_AVAILABLE
HAS_CANCELLED
HAS_CONFIRMED_AFTER_HAVING_CONFIRMED

in the application we just have 
Participe ( validé) 
Annulé
En attente

Can we have more details about the other status, 

2nd point linked to this  we dont totaly get the logic of the workflow to validate  someone on an event 
**How to reproduce it (as minimally and precisely as possible)**:
we set  CONFIRMED, for an event subscriber
 we put HAS_CANCELLED to cancel participation

**What happened**
in both case the sdk anwser is empty 

**What you expected to happen**
we expect a confirmation or maybe it's normal to have  empty result

**Comment by Gobountz** [comment]
@herve-web-isi as explained by email, you don't have to set directly the status of a member. Instead, you have to call event.participate(), event.confirmParticipation() and event.unParticipate() to change your status.

By the way, the missing "confirmParticipation()" has just been added in the 1.0.19 version.

**Comment by davittorosyan** [comment]
@Gobountz event.confirmParticipation() method dont works, please see attachment.
This return error 400 "This action is not valid"
![screen shot 2018-07-02 at 4 59 54 pm](https://user-images.githubusercontent.com/25083334/42165657-c5f07e30-7e19-11e8-8c47-b45aa67d9192.png)

**Comment by Gobountz** [comment]
@davittorosyan, there are several reasons why this operation cannot succeed :
- Firstly, the user (VeloUserName202) attempting to confirm isn't already member of the event. So this call won't confirm the participation, but only make this user a member of the event (BTW, this won't cause an error)
- Secondly, the related event is already past (the start date of the event is on 06/30), this is why the server returned an error

**Comment by davittorosyan** [comment]
@Gobountz thanks, can you please close this issue?
