### ISSUE TITLE
Upcoming events date range issue

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#13]
I have a question related to get upcoming event list
When I am adding date range for events that returns null while we have events for future date.
The code that I am using is in block "List events between two dates" in documentation.
Also please see attchments.

![screen shot 2018-06-26 at 6 13 04 pm](https://user-images.githubusercontent.com/9318170/41918842-3cbf4d12-796e-11e8-9e59-1a888e653021.png)

Swift version: 4.2
xCode version: 9.4.1

Thank You.
Best regards.

**Comment by Gobountz** [comment]
Hi @Valodya89 , indeed I updated the documentation, as an instruction was missing.

You also need to add a call to
```swift
.setDateField(.startDate)
```
to make the search be successful.

You may also upgrade to the 1.0.17 version, as it also make the SDK more stable.

Best regards.

**Comment by Gobountz** [comment]
@Valodya89, do you still have a problem with this point ? Or can this issue be closed ?

Best regards.

**Comment by davittorosyan** [comment]
@Gobountz thank you, it works now
