### ISSUE TITLE
Create account/login mandatory fields

### ISSUE THREAD

**Issue by davittorosyan** [MySocialApp/mysocialapp-swift-client#15]
**Describe the bug**
during account creating now we should set username+email+pass, according java sdk, please change this mandatory fields to email+pass, and please change this also for login function to be logged in with email+pass(now we need set username+pass)

**Comment by Gobountz** [comment]
@davittorosyan the method has been changed to make username optional, but to be retro-compatible, the firstName has not been set to mandatory. Although, please note that the firstName becomes implicitely mandatory, and will be set mandatory in the next release. So please adapt your code to provide a firstName to the createAccount methods from now, to avoid build problems with the upcoming releases.

Best regards.
