### ISSUE TITLE
Search(filter) search function always return nil

### ISSUE THREAD

**Issue by davittorosyan** [MySocialApp/mysocialapp-swift-client#16]
**Describe the bug**
Can you please check function?
Even if we fill good criteria, answer is always empty
![0b72fb9d258cce3e6c819dd3625f43654a84322400ceba054a pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/25083334/42525301-dcfe6c70-8483-11e8-9ce4-083578312689.png)

**Environment**
SDK version is 1.1.1

**Comment by Gobountz** [comment]
Indeed, when using locationMaximumDistance in search, you have to specify the location as well (otherwise you'll get unpredictible results). I updated the README to precise it.

Best regards.
