### ISSUE TITLE
Filter distance problem

### ISSUE THREAD

**Issue by davittorosyan** [MySocialApp/mysocialapp-swift-client#17]
**Describe the bug**
even we sending for distanceInKM 100 km, any case we get from server events which km more than 100

![screen shot 2018-07-16 at 6 54 07 pm](https://user-images.githubusercontent.com/25083334/42768209-f4f11c46-892f-11e8-8bde-b26e9c84679a.png)

result
![cd1da716-18bd-44a6-97f6-ae80b0043660](https://user-images.githubusercontent.com/25083334/42768272-1f0f2c2a-8930-11e8-97cf-2d5b7ef1a77b.jpg)

**Comment by Gobountz** [comment]
@davittorosyan indeed there was a problem, but not in the search feature.
The problem was in the "distanceInMeters" value, which was related to a wrong location.

It is now fixed on server-side.

Best regards.
