### ISSUE TITLE
autocomplete error on search

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#2]
When using the following code with user full name it works

`
let searchQuery = FluentUser.Search.Builder()
        .setFirstName("FirstName")
        .build()
let users = s?.user?.blockingSearch(searchQuery)?.data   <--- crash here when using one letter
`

but when going to use one letter only for autocomplete we are getting the crash.
( please see attachment )

Questions:
Does the search options works for letters?
What will be code example in case when search by letters is possible? 

We have using
Swift version 4.1
Xcode 9.3.1

![error2](https://user-images.githubusercontent.com/9318170/41148458-17ee4a2c-6b1a-11e8-94b7-6fb005985829.png)

Regards

**Comment by evoxmusic** [comment]
@Valodya89 we are going to improve this this week-end. Cheers

**Comment by Gobountz** [comment]
@Valodya89 you can update the version of the SDK you are using to the 1.0.11.
You thus will be able to use the new capabilities of the search feature, for instance for autocomplete :
```swift
// Search every user whom first name starts with the "a" letter
let searchQuery = FluentUser.Search.Builder().setFirstName("a").mustEndWith(false).build()
let users = try? s?.user.blockingSearch(searchQuery)?.data
```

**Comment by Valodya89** [comment]
Thank You!
