### ISSUE TITLE
Event creation - Missing parameters

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#3]
please add event TYPE and Conditions. Icant find this variables in sdk documentation.
![screen shot 2018-06-11 at 6 22 52 pm](https://user-images.githubusercontent.com/9318170/41238201-67fe0578-6da6-11e8-9e14-0311bc328b47.png)

**Comment by Gobountz** [comment]
Hi Valodya,
these properties are part of the "custom fields" feature, which isn't implemented yet in the SDK ; they thus aren't mandatory to create and manage events.

**Comment by Gobountz** [comment]
Hi @Valodya89, the Custom Fields feature has just been released in the last (1.0.14) version of the SDK.

The related documentation is upcoming in the next few hours.

Best regards.

**Comment by Gobountz** [comment]
@Valodya89, the documentation has been updated to explain how to use Custom Fields on Users, Groups and Events (see [Custom Fields](https://github.com/MySocialApp/mysocialapp-swift-client#custom-fields) section in the README).

Also, an example of creating an event with custom fields has been added (see [Create an event](https://github.com/MySocialApp/mysocialapp-swift-client#create-an-event) section).

Best regards.

**Comment by Valodya89** [comment]
@Gobountz When I create an event I can set our custom Fields, it works good , but when I want to get custom field by stringValue i have crash: (CustomField.swift file  row: 79)

FYI: custom fields values added correctly, i can see the values in Android app

Please see attached screenshots

![screen shot 2018-07-04 at 10 15 56 pm](https://user-images.githubusercontent.com/9318170/42292124-4264adb0-7fe1-11e8-8711-70020c50e960.png)

![screen shot 2018-07-04 at 10 12 38 pm](https://user-images.githubusercontent.com/9318170/42292128-4dafc4f2-7fe1-11e8-8261-ba6c369138b4.png)
