### ISSUE TITLE
Event participants statuses issue

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#4]
in sdk documentation i find only basic JOIN event functionality..
How can i set 3 statuses -  invited, joined, rejected?
Can you please show me an code example?

Also, how can i get users for exact event with this 3 statuses?

**Comment by evoxmusic** [comment]
Hi @Valodya89 , these statuses are done automatically but you are right that we need to clarify the documentation and show some examples. cc @Gobountz . I'll let this issue open until it is done. Thanks
