### ISSUE TITLE
Event "MemberAccessControl" issue

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#5]
Even i set access control to "friends of friends", anycase, other users also can see the event i created.
I created new user, who dont have any friend and this user can see the event which i created  for   "friends of friends".

can you please fix this?

**Comment by evoxmusic** [comment]
Hi @Valodya89 , this is normal behavior. All people can see all events, but once Event are set with access_control "Friends of Friends" strangers can not participate to the event. If you want to do not see these events I would suggest to filter them on your client side. We can add (later on) an option to filter them directly through the SDK.
