### ISSUE TITLE
Event joined members list is empty

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#6]
event.members returns always NULL even if i have subscribed users.
Total members returns good count of joined users but events.members no.

Can you show some example?
thanks

**Comment by Gobountz** [comment]
@Valodya89 you can update the version of the SDK you are using to the 1.0.11.
You thus will be able to get members of an event or a group, by calling the .getMembers() (reactive version) or the .blockingGetMembers() (blocking version) ; for instance :
```swift
if let event = try? s?.event.blockingGet(eventId), let members = try? event?.blockingGetMembers(), members != nil {
  let confirmedMembers = members!.filter { $0.status != nil && [EventStatus.Confirmed,EventStatus.WaitingConfirmation,EventStatus.WantToParticipate].contains($0.status!) }
  let users = confirmedMembers.map { $0.user }
}

```

**Comment by Valodya89** [comment]
Thank you!
