### ISSUE TITLE
Incoming Events notification

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#7]
how can i notify users about incoming events?
Can you show me some examples please?

**Comment by evoxmusic** [comment]
Hi Valodya, there is many ways to do it. But I think you need to have real time notifications on new event right ?

If that is the case, we have to implement native or websocket downstream events to make it possible. This is something that we can do within 1 week I guess.

**Comment by Gobountz** [comment]
@Valodya89 we are currently working on providing the APNS capabilities in the MySocialApp Swift SDK. It will allow to provide callbacks for regular notifications, friend requests and private messages notifications, as well as a callback for catching action on native notifications sent by our server and displayed on the notification center of the user.

Please stay tuned on incoming updates of our SDK.

**Comment by Gobountz** [comment]
Realtime notifications are available in the SDK (see https://github.com/MySocialApp/mysocialapp-swift-client#realtime-notifications )

Best regards.
