### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#8]
![screen shot 2018-06-15 at 6 15 27 pm](https://user-images.githubusercontent.com/9318170/41473672-07cf5a9e-70cb-11e8-9430-914ce67c7cee.png)
I have an error from backend when calling most of functions
![screen shot 2018-06-15 at 6 13 55 pm](https://user-images.githubusercontent.com/9318170/41473572-b4575a56-70ca-11e8-8213-70592dcda0eb.png)
, for example this function:

self.userSession = try msa?.blockingConnect(username: name, password: pass)

**MySocialApp was compiled with optimization - stepping may behave oddly; variables may not be available.**

I detect this error message by breakpoint, because when after function running the console is empty.
Also the method of connect() doesnt return anything.

can you please look at this?

**Comment by deimosfr** [comment]
Hi,

Can you please use the issue template. We're lacking information there to help you.

I'm closing the issue.

Thanks for your comprehension
