### ISSUE TITLE
Version update issue

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#9]
Hi I can't update new version (1.0.11)

![screen shot 2018-06-18 at 5 36 29 pm](https://user-images.githubusercontent.com/9318170/41539781-b7244cc4-731f-11e8-97eb-4c997ff52646.png)

When I am trying to update(or setup SDK) by version 1.0.10 it is ok,but when I want to update to new version 1.0.11 from 1.0.10  then I got an error. 
![screen shot 2018-06-18 at 5 36 11 pm](https://user-images.githubusercontent.com/9318170/41539796-c20fd00e-731f-11e8-98e0-2b35cb2491f0.png)

Please see attachments that describing processes to reproduce.

![screen shot 2018-06-18 at 5 34 47 pm](https://user-images.githubusercontent.com/9318170/41539842-d78d7d00-731f-11e8-8e7a-7d40fa80219b.png)

* Swift version: 4.2
* xCode version: 9.4

**Comment by Gobountz** [comment]
Indeed the podspec wasn't pushed to the repository, mea culpa. It is ready now, you can update without any problem now.

Sorry for the inconvenience.

Best regards.

**Comment by Valodya89** [comment]
Update from version 1.0.10 to 1.0.11 done.

Thank You.

**Comment by Valodya89** [comment]
After the update from 1.0.10 to 1.0.11  I got this error

And I can't run my app.

![screen_1](https://user-images.githubusercontent.com/9318170/41566007-7dfd3780-736a-11e8-8158-a7f7cceb8bdb.png)

![screen_2](https://user-images.githubusercontent.com/9318170/41566020-8b4f2a60-736a-11e8-8187-59f52de87e0a.png)
![screen shot 2018-06-19 at 2 05 04 am](https://user-images.githubusercontent.com/9318170/41566022-917397dc-736a-11e8-8afa-e07870e89345.png)
![screen_3](https://user-images.githubusercontent.com/9318170/41566023-96648c56-736a-11e8-89c2-2c4eab9e522b.png)

Can You help me?

Thank You!

Swift version 4.2
xCode version 9.4

**Comment by Gobountz** [comment]
@Valodya89 you may clean your project in XCode by clicking on Product > Clean. Some implicit imports seem to conflict with the previous version's workspace.

Best regards.

**Comment by Valodya89** [comment]
"Clean" is one of my best friends :D but it doesn't help here.
Also I have done several steps
1. manually remove DerivedData
2.Remove Podfile.loc than try pod install / pod update

and always I got same error that I attached above

**Comment by Gobountz** [comment]
@Valodya89 , I can't succeed in reproducing the problem, could you please provide :
- Base SDK version (iOS 11.4 for instance)
- Deployment target (9.0 for instance)
- Details on your pod dependances (name, version, deployment target and Swift language version)

This should help me reproduce the problem, and thus find a solution.

Thank you.

Best regards.

**Comment by herve-web-isi** [comment]
Until the team  give you the information here comes the unblured  version of the pictures

![image](https://user-images.githubusercontent.com/22006286/41658676-6de88506-7497-11e8-9e14-6eacbb8c784c.png)
![screen shot 2018-06-20 at 4 16 35 pm](https://user-images.githubusercontent.com/22006286/41658682-73451f46-7497-11e8-8746-e78752cd046b.png)
![screen shot 2018-06-20 at 4 15 57 pm](https://user-images.githubusercontent.com/22006286/41658685-763222e4-7497-11e8-9e61-b8c6b4c2b158.png)

**Comment by Valodya89** [comment]
@Gobountz  Please see attached screenshots for the points mentioning above

1.
![screen shot 2018-06-20 at 4 18 20 pm](https://user-images.githubusercontent.com/9318170/41663192-e3b263d0-74b3-11e8-87c7-c28563cab23c.png)



2.
![screen shot 2018-06-20 at 5 48 28 pm](https://user-images.githubusercontent.com/9318170/41662708-bf600c0e-74b2-11e8-9f63-2cfe94d49502.png)

3.
![screen shot 2018-06-20 at 5 47 57 pm](https://user-images.githubusercontent.com/9318170/41662750-d56a1ad0-74b2-11e8-85d6-5451a0bf45a6.png)


I noticed that we have in projects repeated same file names
For example
![screen shot 2018-06-20 at 5 45 31 pm](https://user-images.githubusercontent.com/9318170/41663120-be63641c-74b3-11e8-8c52-45cee47268a0.png)
![screen shot 2018-06-20 at 5 46 08 pm](https://user-images.githubusercontent.com/9318170/41663159-c5f99dae-74b3-11e8-8023-57fec2850b1a.png)
![screen shot 2018-06-20 at 5 46 29 pm](https://user-images.githubusercontent.com/9318170/41663164-cb8002e0-74b3-11e8-9da3-59e076816f56.png)


Same file name exists and in our project and in the app sdk.
Could it possible that the problem is there?

**Comment by tigran-e-works** [comment]
I found the problem: problem comea from your (ClientConfiguration.swift) file

Before:
![screen shot 2018-06-20 at 11 31 12 pm](https://user-images.githubusercontent.com/24714846/41680366-57489d0e-74e2-11e8-8f79-cdeec3ca986b.png)

After:
![screen shot 2018-06-20 at 11 30 32 pm](https://user-images.githubusercontent.com/24714846/41680419-7e9ee822-74e2-11e8-9adb-928a1243b088.png)

Attached code before and after.

**Comment by Valodya89** [comment]
@Gobountz  I found the problem: problem comes from your (ClientConfiguration.swift) file

Before:
![screen shot 2018-06-20 at 11 31 12 pm](https://user-images.githubusercontent.com/24714846/41680366-57489d0e-74e2-11e8-8f79-cdeec3ca986b.png)

After:
![screen shot 2018-06-20 at 11 30 32 pm](https://user-images.githubusercontent.com/24714846/41680419-7e9ee822-74e2-11e8-9adb-928a1243b088.png)

Attached code before and after.

I changed some parts and looks like compile successfully done

**Comment by Gobountz** [comment]
@Valodya89 I still cannot succeed in reproducing the problem, even with all your dependencies my build is still stable and OK (however I had to downgrade the Swift version for a couple of your dependencies to 3.3 to make it work).

Even if your trick makes your project build, it doesn't make the system work as expected, as it creates a new scheduler every time the property is used.

I keep on working on this issue, to be continued ...

Best regards.

**Comment by Gobountz** [comment]
@Valodya89 I released the 1.0.12 version, which might build properly. Could you try it and tell me if the problem is fixed ?

Thank you.

Best regards.

**Comment by Valodya89** [comment]
@Gobountz  Thank You

But I still got same error , when I use 1.0.12

**Comment by Gobountz** [comment]
Ok @Valodya89 one more chance : could you please try to build with the 1.0.13 version I just released, and if it fails, could you provide me the full stack trace + stack dump ?

Thank you.

Best regards.

**Comment by Valodya89** [comment]
@Gobountz Thank You for new version.

But I still got same error , when I use 1.0.13

This is Error Logs

https://docs.google.com/document/d/1yF1Fz3u5EZhBIB6jV8ptDZ2Dy6fdYz5_Zs6fHH0znRI/edit?usp=sharing

But when I change "scheduler" by getter its work fine(see attached screen)

![screen shot 2018-06-22 at 11 03 11 am](https://user-images.githubusercontent.com/9318170/41762547-2ec4a456-760c-11e8-9a99-af324fd3d270.png)

**Comment by Gobountz** [comment]
Hi @Valodya89, I finally think I'm done with this problem. You can update the SDK version to 1.0.14 and I hope this will solve your build failure.

The swift compiler seems to badly handle lazy vars in structures. This is a undocumented-but-obvious-for-Apple limitation.

Best regards.
